BEGIN TRANSACTION;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Publisher;
DROP TABLE IF EXISTS BookAuthors;
DROP TABLE IF EXISTS BookCopies;
DROP TABLE IF EXISTS LibraryBranch;
DROP TABLE IF EXISTS BookLoans;
DROP TABLE IF EXISTS Borrower;
COMMIT;